name: Deploy Application

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

  deploy-to-ec2:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Container via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull ghcr.io/${{ github.repository }}:latest
            docker stop my-web-app || true
            docker rm my-web-app || true

            docker network create app-monitoring_default || true

            docker run -d \
              --name my-web-app \
              --restart always \
              --network app-monitoring_default \
              -p 5000:5000 \
              -e DB_HOST=postgres-server \
              -e DB_NAME=db_monitoring \
              -e DB_USER=admin_server \
              -e DB_PASS=PasswordSuperAman123 \
              ghcr.io/${{ github.repository }}:latest
